In [49]:
import pandas as pd
import seaborn as sns
import numpy as np

In [50]:
df = pd.read_csv("C:/Users/ayan1/OneDrive/Documents/Course/Machine Learning Using Python/Data Folder/survey_lung_cancer.csv",header=0)
df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,0
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0

In [51]:
df = pd.get_dummies(df)

In [52]:
df = df.drop(['GENDER_M'],axis=1)

In [53]:
df.head()

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER,GENDER_F
0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1,False
1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1,False
2,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0,True
3,63,2,2,2,1,1,1,1,1,2,1,1,2,2,0,False
4,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0,True

In [54]:
df_corr = df.corr()
LUNG_CANCER_corr = df_corr.LUNG_CANCER.drop(['LUNG_CANCER'],axis=0)

In [55]:
LUNG_CANCER_corr

AGE                      0.089465
SMOKING                  0.058179
YELLOW_FINGERS           0.181339
ANXIETY                  0.144947
PEER_PRESSURE            0.186388
CHRONIC DISEASE          0.110891
FATIGUE                  0.150673
ALLERGY                  0.327766
WHEEZING                 0.249300
ALCOHOL CONSUMING        0.288533
COUGHING                 0.248570
SHORTNESS OF BREATH      0.060738
SWALLOWING DIFFICULTY    0.259730
CHEST PAIN               0.190451
GENDER_F                -0.067254
Name: LUNG_CANCER, dtype: float64

In [56]:
from sklearn.linear_model import LogisticRegression

x = df[['SMOKING']]
y = df['LUNG_CANCER']

model = LogisticRegression()
model.fit(x, y)

print("Intercept: ",model.intercept_[0],"\nCoefficients: ",model.coef_[0][0])

Intercept:  1.454745666332932
Coefficients:  0.31294235206785015

In [57]:
from sklearn.model_selection import train_test_split

x_multi = df.drop(['LUNG_CANCER'], axis=1).astype(float)
y_multi = df['LUNG_CANCER'].astype(float)  # Convert to integer

x_train, x_test, y_train, y_test = train_test_split(x_multi, y_multi, test_size=0.2, random_state=5)

model = LogisticRegression(max_iter=500)  # Increase the number of iterations
model.fit(x_train, y_train)

print("Intercept: ", model.intercept_[0])
print("Coefficients: ", model.coef_[0])

Intercept:  -17.313332825564583
Coefficients:  [ 0.02774492  0.77124285  0.77423834  0.74067156  1.12680908  1.46566892
  1.24785425  1.46036733  0.72239601  1.34093462  1.21751279 -0.07607328
  0.98853042  0.39270303 -0.05892611]